export const SET_LOADING = 'SET_LOADING';
export const CLEAR_USERS = 'CLEAR_USERS';
export const SEARCH_USERS = 'SEARCH_USERS';
export const GET_USER_BY_LOGIN = 'GET_USER_BY_LOGIN';
export const GET_USER_REPOS_BY_LOGIN = 'GET_USER_REPOS_BY_LOGIN';
export const SHOW_ALERT = 'SHOW_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
